<?xml version="1.0"?>
<package format="3">
  <name>tp5_navigation</name>
  <version>0.0.1</version>
  <description>TP5 Navigation autonome avec évitement d'obstacles</description>
  <maintainer email="yasmin@todo.com">yasmin</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>behaviortree_cpp</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
